using Newtonsoft.Json;
using StackExchange.Redis;
using System;
using System.Collections.Generic;
using System.Text;

namespace RedisSubscriber
{
    class RedisSub : RedisConnect
    {
        private ISubscriber _subscriber { get; set; }

        public RedisSub()
        {
            _subscriber = Redis.Multiplexer.GetSubscriber();
        }
        public override void PrintValues(bool deleteKeys = false)
        {
            _subscriber.Subscribe("test*").OnMessage((channelMessage) =>
            {
                Message msg = JsonConvert.DeserializeObject<Message>(channelMessage.Message);
                Console.WriteLine("Got notification");
                Console.WriteLine($"Message Title : {msg.MessageTitle}");
                Console.WriteLine($"Message Description : {msg.MessageDescription}");
                Console.WriteLine($"Message Generated By : {msg.MessageGeneratedBy}");
                Console.WriteLine($"Message Generated At : {msg.MessageGeneratedAt}");
            });
        }
    }
}
